version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockers/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./logging:/app/logging
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOGURU_AUTO_REMOVE=True
    depends_on:
      - redis
    command: uvicorn app.main:godeye_api --host 0.0.0.0
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"